# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_helloextendr_wrappers", use_symbols = TRUE, package_name = "helloextendr")

#' @docType package
#' @usage NULL
#' @useDynLib helloextendr, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' show case persist memory between calls to rust
#' @export
MyHiker <- new.env(parent = emptyenv())

MyHiker$new <- function(l) .Call(wrap__MyHiker__new, l)

MyHiker$print <- function() invisible(.Call(wrap__MyHiker__print, self))

#' @rdname MyHiker
#' @usage NULL
#' @export
`$.MyHiker` <- function (self, name) { func <- MyHiker[[name]]; environment(func) <- environment(); func }

#' @export
`[[.MyHiker` <- `$.MyHiker`


# nolint end
